@extends('layouts.admin')
@section('title', 'Booking Codes')
@section('page-title', 'Booking Codes')

@section('content')
<style>
    .book-stats { display:grid;grid-template-columns:repeat(5,minmax(0,1fr));gap:.7rem;margin-bottom:1rem; }
    .book-stat { background:linear-gradient(135deg,rgba(20,37,57,.96),rgba(13,26,39,.96));border:1px solid var(--border);border-radius:11px;padding:.8rem .9rem; }
    .book-stat b { display:block;color:#fff;font-size:1.2rem; } .book-stat span { color:var(--dim);font-size:.68rem; }
    .book-grid { display:grid;grid-template-columns:minmax(0,1.35fr) minmax(280px,.65fr);gap:1rem;margin-bottom:1rem; }
    .book-label { display:block;font-size:.7rem;color:var(--dim);font-weight:700;margin-bottom:.3rem; } .book-input { width:100%;box-sizing:border-box;background:rgba(255,255,255,.045);border:1px solid var(--border);border-radius:7px;color:#fff;padding:.58rem .68rem;font-size:.8rem; }
    .book-input:focus { outline:none;border-color:rgba(45,212,191,.65);box-shadow:0 0 0 3px rgba(45,212,191,.08); }
    .book-primary,.book-secondary,.book-danger { border-radius:8px;padding:.56rem .75rem;cursor:pointer;font-size:.74rem;font-weight:850; } .book-primary { background:#1eaa9b;color:#071715;border:1px solid #4be1d0; } .book-secondary { background:rgba(255,255,255,.04);color:#dbe7f3;border:1px solid var(--border); } .book-danger { background:rgba(239,68,68,.1);color:#fca5a5;border:1px solid rgba(239,68,68,.33); }
    .book-status { padding:.22rem .45rem;border-radius:999px;font-size:.65rem;font-weight:850;text-transform:uppercase; } .book-status.published { background:rgba(45,212,191,.1);border:1px solid rgba(45,212,191,.3);color:#69e8dc; } .book-status.won { background:rgba(52,211,153,.1);border:1px solid rgba(52,211,153,.3);color:#74f4c7; } .book-status.lost,.book-status.failed { background:rgba(251,113,133,.1);border:1px solid rgba(251,113,133,.3);color:#fda4af; } .book-status.pending,.book-status.expired { background:rgba(245,158,11,.09);border:1px solid rgba(245,158,11,.3);color:#f8cf72; }
    .book-op { padding:1rem;border-radius:11px;border:1px solid var(--border);background:rgba(255,255,255,.018); } .book-op h3 { margin:0 0 .35rem;color:#fff;font-size:.86rem; } .book-op p { margin:0;color:var(--dim);font-size:.73rem;line-height:1.55; }
    .book-legs { margin-top:.35rem; } .book-legs summary { cursor:pointer;color:#71e8dd;font-size:.67rem;font-weight:800; } .book-legs ul { list-style:none;margin:.4rem 0 0;padding:0;min-width:230px; } .book-legs li { padding:.32rem 0;border-bottom:1px solid rgba(255,255,255,.06);font-size:.66rem;color:var(--dim);display:flex;justify-content:space-between;gap:.5rem; } .book-leg-state { font-weight:850;text-transform:uppercase;font-size:.58rem; } .book-leg-state.won{color:#74f4c7}.book-leg-state.lost{color:#fda4af}.book-leg-state.pending,.book-leg-state.unresolved{color:#f8cf72}.book-leg-state.void{color:#9ca3af}
    .book-date-nav { display:flex;align-items:center;gap:.5rem;flex-wrap:wrap;justify-content:flex-end; }.book-date-nav a,.book-date-nav span { border:1px solid var(--border);border-radius:8px;padding:.45rem .62rem;color:#dbe7f3;font-size:.7rem;font-weight:800;text-decoration:none; }.book-date-nav a:hover { border-color:rgba(45,212,191,.55);color:#71e8dd; }.book-date-picker { min-height:34px;background:rgba(255,255,255,.045);border:1px solid rgba(45,212,191,.32);border-radius:8px;color:#fff;padding:.3rem .5rem;font-size:.72rem;color-scheme:dark; }
    @media(max-width:820px){.book-stats{grid-template-columns:repeat(3,1fr)}.book-grid{grid-template-columns:1fr}.book-history th:nth-child(5),.book-history td:nth-child(5){display:none}} @media(max-width:520px){.book-stats{grid-template-columns:repeat(2,1fr)}.book-stats .book-stat:last-child{grid-column:1/-1}.book-history th:nth-child(4),.book-history td:nth-child(4){display:none}}
</style>

<div class="page-hd"><span class="page-hd-title">🎟️ Booking code desk</span><span style="font-size:.72rem;color:var(--dim)">Automated tickets, verified outcomes, and distribution.</span></div>
@if(session('success'))<div style="background:rgba(45,212,191,.1);border:1px solid rgba(45,212,191,.3);border-radius:9px;padding:.72rem .9rem;margin-bottom:1rem;font-size:.78rem;color:#71e8dd;">✓ {{ session('success') }}</div>@endif
@if(session('error'))<div style="background:rgba(251,113,133,.1);border:1px solid rgba(251,113,133,.3);border-radius:9px;padding:.72rem .9rem;margin-bottom:1rem;font-size:.78rem;color:#fda4af;">⚠ {{ session('error') }}</div>@endif

<div class="book-stats"><div class="book-stat"><b>{{ $stats['total'] }}</b><span>All codes</span></div><div class="book-stat"><b>{{ $stats['published'] }}</b><span>Awaiting outcome</span></div><div class="book-stat"><b style="color:#74f4c7">{{ $stats['won'] }}</b><span>Won</span></div><div class="book-stat"><b style="color:#fda4af">{{ $stats['lost'] }}</b><span>Lost</span></div><div class="book-stat"><b>2.00+</b><span>Minimum odds</span></div></div>

<div class="book-grid">
    <section class="a-card">
        <div class="page-hd" style="margin-bottom:.85rem"><span style="font-size:.9rem;font-weight:850;color:#fff">Publish a manual booking code</span></div>
        <form method="POST" action="{{ route('admin.booking-code.send') }}">@csrf
            <div style="display:grid;grid-template-columns:1fr 1fr;gap:.7rem;margin-bottom:.7rem">
                <div><label class="book-label">Sportsbook</label><select name="platform" class="book-input" required><option value="SportyBet">SportyBet</option><option value="Bet9ja">Bet9ja</option><option value="1xBet">1xBet</option><option value="1Win">1Win</option><option value="Betway">Betway</option><option value="Parimatch">Parimatch</option><option value="BetKing">BetKing</option><option value="NairaBet">NairaBet</option></select>@error('platform')<small style="color:#fda4af">{{ $message }}</small>@enderror</div>
                <div><label class="book-label">Booking code</label><input class="book-input" style="font-family:monospace;text-transform:uppercase" name="code" value="{{ old('code') }}" placeholder="ABC12345" required>@error('code')<small style="color:#fda4af">{{ $message }}</small>@enderror</div>
            </div>
            <div style="display:grid;grid-template-columns:1fr 1fr;gap:.7rem;margin-bottom:.7rem"><div><label class="book-label">Total odds <span style="color:#f8cf72">(minimum 2.00)</span></label><input class="book-input" type="number" min="2" max="500" step="0.01" name="total_odds" value="{{ old('total_odds') }}" placeholder="2.00" required>@error('total_odds')<small style="color:#fda4af">{{ $message }}</small>@enderror</div><div><label class="book-label">Pick date</label><input class="book-input" type="date" name="pick_date" value="{{ old('pick_date', now('Africa/Lagos')->toDateString()) }}" required>@error('pick_date')<small style="color:#fda4af">{{ $message }}</small>@enderror</div></div>
            <div style="margin-bottom:.8rem"><label class="book-label">Short ticket note</label><input class="book-input" name="note" value="{{ old('note') }}" placeholder="e.g. Today's safest goal-line ticket">@error('note')<small style="color:#fda4af">{{ $message }}</small>@enderror</div>
            <button class="book-primary" type="submit">Publish to Telegram &amp; push</button>
        </form>
        <p style="color:var(--dim);font-size:.69rem;line-height:1.5;margin:.8rem 0 0">Manual codes are shared normally. Automatic win/loss grading requires an automated ticket with saved fixture selections.</p>
    </section>
    <aside style="display:grid;gap:.7rem;align-content:start">
        <div class="book-op" style="border-color:rgba(45,212,191,.34);background:linear-gradient(135deg,rgba(45,212,191,.09),rgba(15,23,42,.04));">
            <h3>⚡ Generate real codes</h3>
            <p>Queues a secure request for your Mac worker. The Mac opens SportyBet, verifies the current odds and only sends back usable codes with 3+ legs and 2.00+ total odds.</p>
            @if($generationRequest)
                <div style="margin-top:.65rem;padding:.5rem .6rem;border-radius:7px;background:rgba(251,191,36,.1);color:#fde68a;font-size:.7rem;line-height:1.4;">⏳ Waiting for the Mac worker since {{ \Carbon\Carbon::parse($generationRequest['requested_at'])->timezone('Africa/Lagos')->format('H:i') }} Lagos.</div>
            @endif
            <form method="POST" action="{{ route('admin.booking-code.generate') }}" style="margin-top:.65rem" onsubmit="return confirm('Ask the Mac worker to generate today\'s real SportyBet booking codes now? Only qualified tickets will be published.');">@csrf<button class="book-primary" type="submit" {{ $workerReady ? '' : 'disabled' }}>⚡ Generate codes on Mac</button></form>
            @unless($workerReady)<small style="display:block;margin-top:.45rem;color:#fda4af;font-size:.66rem;">Add BOOKING_WORKER_TOKEN before this can run.</small>@endunless
        </div>
        <div class="book-op"><h3>{{ $workerReady ? '✓ Worker token configured' : '⚠ Worker token missing' }}</h3><p>{{ $workerReady ? 'Keep watch.sh running on the Mac so it can collect Generate requests, pull qualified tickets and post real codes back to this desk.' : 'Set BOOKING_WORKER_TOKEN in the application and worker environments before automatic publishing.' }}</p></div>
        <div class="book-op"><h3>Outcome monitor</h3><p>The scheduler checks every 30 minutes. Run it now after final scores arrive.</p><form method="POST" action="{{ route('admin.booking-code.grade') }}" style="margin-top:.65rem">@csrf<button class="book-secondary" type="submit">Check outcomes now</button></form></div>
        <div class="book-op"><h3>Telegram delivery</h3><p>Re-send today's active codes with the Copy Code and Open Ticket buttons. This does not create duplicate codes.</p><form method="POST" action="{{ route('admin.booking-code.resend') }}" style="margin-top:.65rem">@csrf<button class="book-secondary" type="submit">Re-send today's codes</button></form></div>
        <div class="book-op" style="border-color:rgba(239,68,68,.26)"><h3>Fresh start</h3><p>Deletes every booking code and outcome history only. It does not change predictions, fixtures, or user accounts.</p><form method="POST" action="{{ route('admin.booking-code.clear') }}" onsubmit="return confirm('Delete every booking code and its outcome history? This cannot be undone.');" style="margin-top:.65rem">@csrf<button class="book-danger" type="submit">Delete all booking codes</button></form></div>
    </aside>
</div>

<section class="a-card"><div class="page-hd" style="margin-bottom:.8rem"><div><span style="font-size:.9rem;font-weight:850;color:#fff">{{ $isToday ? "Today's booking codes" : 'Booking codes · '.$selectedDate->format('D, d M Y') }}</span><span style="display:block;font-size:.7rem;color:var(--dim);margin-top:.2rem">{{ $history->whereIn('status', ['won', 'lost'])->count() }} settled ticket(s) on this date</span></div><nav class="book-date-nav" aria-label="Booking-code date navigation"><a href="{{ route('admin.booking-code.index', ['date' => $previousDate]) }}">← Previous</a><form method="GET" action="{{ route('admin.booking-code.index') }}"><label for="admin-booking-date" class="sr-only">Choose booking-code date</label><input id="admin-booking-date" class="book-date-picker" type="date" name="date" value="{{ $selectedDate->toDateString() }}" max="{{ now('Africa/Lagos')->toDateString() }}" onchange="this.form.submit()"></form>@if($nextDate)<a href="{{ route('admin.booking-code.index', ['date' => $nextDate]) }}">Next →</a>@else<span style="opacity:.45">Today</span>@endif</nav></div>
@if($history->isEmpty())<div style="text-align:center;padding:2rem;color:var(--dim);font-size:.8rem">No booking codes yet.</div>@else
<div style="overflow-x:auto"><table class="a-table book-history"><thead><tr><th>Published</th><th>Platform / code</th><th>Outcome</th><th>Odds</th><th>Ticket &amp; saved legs</th><th></th></tr></thead><tbody>@foreach($history as $item)<tr><td style="font-size:.71rem;color:var(--dim);white-space:nowrap">{{ $item->created_at->setTimezone('Africa/Lagos')->format('M d, H:i') }}</td><td><b style="font:.78rem ui-monospace,SFMono-Regular,Menlo,monospace;color:#fff">{{ strtoupper($item->code) }}</b><small style="display:block;color:var(--dim);font-size:.65rem">{{ str_starts_with((string) $item->slip_ref, 'tennis-') ? '🎾 Tennis' : '⚽ Football' }} · {{ $item->platform }} · {{ $item->source }}</small></td><td><span class="book-status {{ $item->status }}">{{ $item->status }}</span>@if($item->settled_at)<small style="display:block;color:var(--dim);font-size:.63rem;margin-top:.25rem">{{ $item->settled_at->setTimezone('Africa/Lagos')->format('M d, H:i') }}</small>@endif</td><td style="color:#f8cf72;font-weight:800;font-size:.75rem">{{ $item->total_odds ? number_format((float)$item->total_odds,2) : 'N/A' }}</td><td style="color:var(--dim);font-size:.7rem">{{ $item->note ?: ($item->slip_ref ?: 'N/A') }}@if($item->legs->isNotEmpty())<details class="book-legs"><summary>View {{ $item->legs->count() }} legs · {{ $item->legs->where('status','won')->count() }} won</summary><ul>@foreach($item->legs as $leg)<li><span>{{ $leg->home_team }} vs {{ $leg->away_team }}<br><b style="color:#c8d6e5">{{ $leg->market }}</b>@if($leg->home_score !== null)<br>{{ $leg->home_score }}:{{ $leg->away_score }}@endif</span><span class="book-leg-state {{ $leg->status }}">{{ $leg->status }}</span></li>@endforeach</ul></details>@endif</td><td><form method="POST" action="{{ route('admin.booking-code.destroy',$item) }}" onsubmit="return confirm('Delete this booking code?')">@csrf @method('DELETE')<button class="book-danger" type="submit">Delete</button></form></td></tr>@endforeach</tbody></table></div>@endif</section>

<section class="a-card" style="margin-top:1rem"><div class="page-hd" style="margin-bottom:.55rem"><span style="font-size:.9rem;font-weight:850;color:#fff">Booking feedback used by the ticket builder</span></div><p style="margin:0 0 .75rem;color:var(--dim);font-size:.72rem;line-height:1.55">This is a selected-ticket safety signal, kept separate from the platform’s full prediction calibration so results are never double-counted. After 20 settled legs, a market below 50% is paused from new booking tickets until its record recovers.</p>@if(empty($learningFeedback))<div style="color:var(--dim);font-size:.75rem">No settled automated booking legs yet.</div>@else<div style="overflow-x:auto"><table class="a-table"><thead><tr><th>Market</th><th>Settled legs</th><th>Won</th><th>Win rate</th><th>Ticket builder</th></tr></thead><tbody>@foreach($learningFeedback as $market => $feedback)<tr><td style="font-size:.73rem;color:#fff">{{ $market }}</td><td>{{ $feedback['settled'] }}</td><td style="color:#74f4c7">{{ $feedback['wins'] }}</td><td>{{ number_format($feedback['win_rate'],1) }}%</td><td style="font-size:.7rem;color:{{ $feedback['settled'] >= 20 && $feedback['win_rate'] < 50 ? '#fda4af' : '#74f4c7' }}">{{ $feedback['settled'] >= 20 && $feedback['win_rate'] < 50 ? 'Paused for review' : 'Eligible / building sample' }}</td></tr>@endforeach</tbody></table></div>@endif</section>
@endsection
