@extends('layouts.app')
@section('title', "Today's {$config['title']} Picks | TavsScore")
@section('meta_description', "Today's AI-selected {$config['title']} football picks, with model probability and match analysis.")
@section('content')
<style>
.sp-shell{max-width:1120px;margin:0 auto;padding:2rem 1rem 4rem}.sp-hero{background:radial-gradient(circle at top right,#164e63,#101827 55%,#080d18);border:1px solid rgba(148,163,184,.22);border-radius:24px;padding:clamp(1.35rem,4vw,3rem);color:#fff}.sp-kicker{color:#67e8f9;font-size:.74rem;font-weight:800;letter-spacing:.14em;text-transform:uppercase}.sp-title{font-size:clamp(2rem,6vw,4.2rem);line-height:1.02;margin:.45rem 0 .8rem}.sp-sub{max-width:650px;color:#cbd5e1;line-height:1.6}.sp-stats{display:flex;gap:.75rem;flex-wrap:wrap;margin-top:1.5rem}.sp-stat{padding:.7rem 1rem;border-radius:14px;background:rgba(255,255,255,.08);font-size:.84rem}.sp-date{display:flex;align-items:center;justify-content:space-between;gap:1rem;margin:1.3rem 0;flex-wrap:wrap}.sp-date a{color:#0f172a;background:#e2e8f0;padding:.55rem .75rem;border-radius:10px;text-decoration:none;font-weight:700}.sp-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:1rem}.sp-card{background:#fff;border:1px solid #e2e8f0;border-radius:20px;padding:1.15rem;box-shadow:0 7px 20px rgba(15,23,42,.06)}.sp-rank{color:#0891b2;font-size:.72rem;font-weight:900}.sp-match{font-size:1.18rem;font-weight:850;color:#0f172a;margin:.35rem 0}.sp-league{font-size:.77rem;color:#64748b}.sp-pick{margin:1rem 0;padding:.85rem;border-radius:13px;background:#ecfeff;color:#155e75;font-weight:800}.sp-meta{display:flex;justify-content:space-between;color:#475569;font-size:.82rem}.sp-result{font-weight:900}.sp-win{color:#15803d}.sp-loss{color:#dc2626}.sp-info{margin-top:1.4rem;padding:1rem;border-radius:14px;background:#f8fafc;color:#475569;line-height:1.55}.sp-empty{text-align:center;padding:3rem;color:#64748b;background:#fff;border:1px dashed #cbd5e1;border-radius:18px}@media(max-width:650px){.sp-grid{grid-template-columns:1fr}.sp-shell{padding:.9rem .75rem 3rem}.sp-hero{border-radius:18px}.sp-date{align-items:stretch}.sp-date a{flex:1;text-align:center}.sp-title{font-size:2.25rem}}
</style>
<main class="sp-shell">
 <section class="sp-hero"><div class="sp-kicker">{{ $config['icon'] }} TavsScore specialty market</div><h1 class="sp-title">{{ $config['title'] }}</h1><p class="sp-sub">A focused daily slate, selected from the model’s full match board. We publish only the fixtures that clear the market’s probability threshold.</p><div class="sp-stats"><span class="sp-stat"><strong>{{ $accuracy['pct'] ?? '—' }}%</strong> settled accuracy</span><span class="sp-stat">{{ $accuracy['correct'] }}/{{ $accuracy['total'] }} settled picks</span><span class="sp-stat">Up to 5 picks daily</span></div></section>
 <div class="sp-date"><a href="{{ route($dateMeta['route'], ['date' => $dateMeta['prev_iso']]) }}">← Previous day</a><strong>{{ $dateMeta['pretty'] }}</strong>@if($dateMeta['next_iso'])<a href="{{ route($dateMeta['route'], ['date' => $dateMeta['next_iso']]) }}">Next day →</a>@endif</div>
 @if($formatted->isNotEmpty())<section class="sp-grid">@foreach($formatted as $pick)<article class="sp-card"><div class="sp-rank">SIGNAL #{{ $pick['rank'] }}</div><div class="sp-match">{{ $pick['match']['home'] }} <span style="color:#94a3b8">vs</span> {{ $pick['match']['away'] }}</div><div class="sp-league">{{ $pick['match']['league'] }} · {{ $pick['match']['time'] }}</div><div class="sp-pick">{{ $pick['label'] }} <span style="float:right">{{ $pick['prob'] }}%</span></div><div class="sp-meta"><span>{{ $pick['score'] ?: ($pick['match']['status'] ?: 'Scheduled') }}</span>@if($pick['result'] !== null)<span class="sp-result {{ $pick['result'] ? 'sp-win' : 'sp-loss' }}">{{ $pick['result'] ? '✓ WON' : '✕ LOST' }}</span>@endif</div></article>@endforeach</section>@else<div class="sp-empty"><h2>No qualified picks yet</h2><p>Today’s fixtures are still being analysed. Check back shortly.</p></div>@endif
 <div class="sp-info">@if($config['type'] === 'handicap')<strong>How handicap picks work:</strong> We use Asian half-goal lines from 0.5 to 5.5. The selected team’s score is adjusted by the displayed line, so there is no draw/void outcome to misreport. @else<strong>How this market works:</strong> Each pick must clear a strict probability floor from our statistical match model before it is published. @endif Predictions are analysis, not guarantees. Please gamble responsibly.</div>
</main>
@endsection
