@extends('layouts.admin')
@section('title', 'Shalom AI Lab')
@section('page-title', 'Shalom AI Lab')
@section('content')
<style>
.sa-hero{padding:1.2rem;border:1px solid rgba(45,212,191,.28);background:radial-gradient(circle at 90% 10%,rgba(45,212,191,.15),transparent 35%),#101d2b;border-radius:14px;margin-bottom:1rem}.sa-hero h2{margin:0;color:#fff;font-size:1.2rem}.sa-hero p{color:var(--dim);font-size:.76rem;line-height:1.55;margin:.4rem 0 0}.sa-actions{display:flex;flex-wrap:wrap;gap:.55rem;margin-top:.85rem}.sa-btn{border-radius:8px;padding:.55rem .75rem;background:rgba(45,212,191,.12);border:1px solid rgba(45,212,191,.35);color:#72e7dd;font-size:.72rem;font-weight:850;cursor:pointer}.sa-btn.secondary{background:rgba(255,255,255,.04);border-color:var(--border);color:#d9e4ef}.sa-stats{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:.65rem;margin:1rem 0}.sa-stat{background:var(--card);border:1px solid var(--border);border-radius:10px;padding:.75rem}.sa-stat b{display:block;color:#fff;font-size:1.15rem}.sa-stat span{font-size:.65rem;color:var(--dim)}.sa-card{background:var(--card);border:1px solid var(--border);border-radius:11px;padding:1rem;margin-top:1rem}.sa-card h3{font-size:.85rem;color:#fff;margin:0 0 .65rem}.sa-table{width:100%;border-collapse:collapse;font-size:.73rem}.sa-table th,.sa-table td{padding:.55rem .35rem;border-bottom:1px solid rgba(255,255,255,.06);text-align:left}.sa-table th{color:var(--dim);font-size:.61rem;text-transform:uppercase}.sa-win{color:#74f4c7;font-weight:800}.sa-loss{color:#fda4af;font-weight:800}.sa-pending{color:#f8cf72;font-weight:800}.sa-draft{padding:.75rem 0;border-bottom:1px solid var(--border)}.sa-draft:last-child{border-bottom:0}.sa-draft h4{color:#fff;font-size:.78rem;margin:0}.sa-draft p{font-size:.7rem;color:var(--dim);line-height:1.5;margin:.35rem 0 0}@media(max-width:650px){.sa-stats{grid-template-columns:1fr 1fr}.sa-table{min-width:590px}}
</style>
<div class="sa-hero"><h2>✦ Shalom AI, private shadow lab</h2><p>First-party score model trained from verified final football scores. It has no access to public picks, notifications, booking codes, or published articles. Its record must prove itself here before any future promotion.</p><div class="sa-actions"><form method="POST" action="{{ route('admin.shalom-ai.train') }}">@csrf<button class="sa-btn" type="submit">Train from verified results</button></form><form method="POST" action="{{ route('admin.shalom-ai.predict') }}">@csrf<button class="sa-btn secondary" type="submit">Generate shadow predictions</button></form><form method="POST" action="{{ route('admin.shalom-ai.settle') }}">@csrf<button class="sa-btn secondary" type="submit">Check outcomes</button></form><form method="POST" action="{{ route('admin.shalom-ai.draft') }}">@csrf<button class="sa-btn secondary" type="submit">Write private blog draft</button></form></div></div>
@if(session('success'))<div style="padding:.7rem .85rem;border:1px solid rgba(45,212,191,.28);border-radius:9px;color:#70e7dc;background:rgba(45,212,191,.08);font-size:.74rem;margin-bottom:1rem;white-space:pre-line">{{ session('success') }}</div>@endif
<div class="sa-stats"><div class="sa-stat"><b>{{ $stats['total'] }}</b><span>Shadow predictions</span></div><div class="sa-stat"><b>{{ $stats['settled'] }}</b><span>Settled independently</span></div><div class="sa-stat"><b>{{ $stats['wins'] }}</b><span>Correct outcomes</span></div><div class="sa-stat"><b>{{ $stats['hit_rate'] === null ? 'N/A' : $stats['hit_rate'].'%' }}</b><span>Shadow hit rate</span></div></div>
<section class="sa-card"><h3>Independent prediction record</h3><div style="overflow-x:auto"><table class="sa-table"><thead><tr><th>Fixture</th><th>Kickoff</th><th>Shalom AI pick</th><th>1X2 probabilities</th><th>Result</th></tr></thead><tbody>@forelse($predictions as $p)<tr><td style="color:#fff;font-weight:750">{{ $p->match?->home_team }} vs {{ $p->match?->away_team }}<small style="display:block;color:var(--dim);font-weight:400">{{ $p->match?->league }}</small></td><td style="color:var(--dim)">{{ $p->match?->match_time?->timezone('Africa/Lagos')->format('M d H:i') }}</td><td><b style="color:#70e7dc">{{ $p->predicted_outcome }}</b><small style="display:block;color:var(--dim)">{{ $p->confidence }}% confidence</small></td><td>{{ number_format($p->home_win_probability,1) }} / {{ number_format($p->draw_probability,1) }} / {{ number_format($p->away_win_probability,1) }}</td><td>@if($p->was_correct === true)<span class="sa-win">✓ Won</span>@elseif($p->was_correct === false)<span class="sa-loss">× Lost</span>@else<span class="sa-pending">Pending</span>@endif</td></tr>@empty<tr><td colspan="5" style="padding:2rem;text-align:center;color:var(--dim)">Train Shalom AI first, then generate its private predictions.</td></tr>@endforelse</tbody></table></div></section>
<section class="sa-card"><h3>Private Shalom AI editorial drafts</h3><p style="font-size:.7rem;color:var(--dim);margin-top:-.35rem">Data-grounded match previews only. They are never public posts and need editorial review before being copied into the normal Blog editor.</p>@forelse($drafts as $draft)<article class="sa-draft"><h4>{{ $draft->title }}</h4><p>{{ $draft->excerpt }} · {{ $draft->generated_at->diffForHumans() }}</p><details style="margin-top:.45rem"><summary style="color:#70e7dc;font-size:.69rem;cursor:pointer">Read draft</summary><div style="font-size:.73rem;color:#c9d6e3;line-height:1.6;margin-top:.5rem">{!! $draft->content !!}</div></details></article>@empty<div style="color:var(--dim);font-size:.74rem;padding:.6rem 0">No private drafts yet.</div>@endforelse</section>
@endsection
