@extends('layouts.app')
@section('title', ($match->player_one . ' vs ' . $match->player_two) . ' Tennis Prediction | TavsScore')
@section('meta_description', 'TavsScore tennis match analysis, player probabilities and surface-aware model context.')
@push('styles')
<style>
.td-page{max-width:1000px;margin:0 auto;padding:1.2rem 1rem 4rem}.td-back{display:inline-flex;color:var(--text-dim);font-size:.78rem;font-weight:800;text-decoration:none;margin:.25rem 0 1rem}.td-main{position:relative;overflow:hidden;border:1px solid rgba(255,255,255,.14);border-radius:24px;padding:clamp(1.25rem,4vw,3rem);background:linear-gradient(130deg,#091b12,#123c25)}.td-main:before{content:"";position:absolute;inset:0;background:linear-gradient(100deg,rgba(3,13,8,.94),rgba(3,13,8,.55),rgba(3,13,8,.16));pointer-events:none}.td-content{position:relative}.td-meta{font-size:.7rem;color:#c7eea5;font-weight:900;letter-spacing:.1em;text-transform:uppercase}.td-title{margin:.65rem 0;color:#fff;font-size:clamp(2rem,5vw,4.1rem);letter-spacing:-.06em;line-height:.96}.td-title span{color:#d9ff79}.td-time{color:#d5e4da;font-size:.85rem}.td-board{margin-top:1.7rem;border:1px solid rgba(217,255,121,.18);border-radius:16px;background:rgba(2,12,8,.45);padding:1rem}.td-names,.td-probs{display:flex;justify-content:space-between;gap:1rem;font-size:.82rem;font-weight:800}.td-names{color:#fff}.td-probs{color:#d9ff79;margin-top:.45rem}.td-rail{display:flex;height:13px;overflow:hidden;border-radius:999px;background:rgba(255,255,255,.08);margin:.65rem 0}.td-one{background:#d9ff79}.td-two{background:#34b778}.td-pick{margin-top:1rem;color:#efffd4;font-size:.88rem;font-weight:900}.td-grid{display:grid;grid-template-columns:1.2fr .8fr;gap:1rem;margin-top:1rem}.td-card{background:var(--card);border:1px solid var(--border);border-radius:18px;padding:1.15rem}.td-label{color:var(--text-dim);font-size:.68rem;text-transform:uppercase;letter-spacing:.1em;font-weight:900}.td-analysis{color:var(--text);line-height:1.72;font-size:.9rem;margin:.65rem 0 0}.td-signals{display:grid;gap:.7rem;margin-top:.75rem}.td-signal{display:flex;justify-content:space-between;gap:.7rem;padding:.65rem .75rem;border-radius:10px;background:rgba(217,255,121,.06);color:var(--text);font-size:.78rem}.td-signal span:last-child{color:#d9ff79;font-weight:850}.td-result{margin-top:.8rem;font-size:.82rem;font-weight:900}.td-won{color:#72e8a2}.td-lost{color:#f5a3a3}@media(max-width:700px){.td-page{padding:.75rem .72rem 3rem}.td-main{border-radius:18px}.td-main:before{background:linear-gradient(0deg,rgba(3,13,8,.94),rgba(3,13,8,.52))}.td-grid{grid-template-columns:1fr}.td-title{font-size:2.45rem}}</style>
@endpush
@section('content')
@php($features=is_array($prediction->features)?$prediction->features:[];$one=$features['one']??[];$two=$features['two']??[];$h2h=$features['h2h']??[])
<main class="td-page"><a class="td-back" href="{{ route('tennis.index') }}">← Back to tennis signals</a><section class="td-main" @if($heroImage) style="background-image:linear-gradient(100deg,rgba(3,13,8,.94),rgba(3,13,8,.48)),url('{{ asset($heroImage) }}');background-size:cover;background-position:center;" @endif><div class="td-content"><div class="td-meta">{{ $match->tour }} · {{ $match->tournament }} · {{ $match->surface ?: 'Surface pending' }}</div><h1 class="td-title">{{ $match->player_one }} <span>vs</span> {{ $match->player_two }}</h1><div class="td-time">{{ $match->scheduled_at?->timezone(config('app.timezone'))->format('l, M j · H:i') ?? $match->match_date?->format('l, M j') }}</div><div class="td-board"><div class="td-names"><span>{{ $match->player_one }}</span><span>{{ $match->player_two }}</span></div><div class="td-rail"><span class="td-one" style="width:{{ $prediction->player_one_win_prob }}%"></span><span class="td-two" style="width:{{ $prediction->player_two_win_prob }}%"></span></div><div class="td-probs"><span>{{ number_format($prediction->player_one_win_prob,1) }}%</span><span>{{ number_format($prediction->player_two_win_prob,1) }}%</span></div><div class="td-pick">🎯 Model pick: {{ $prediction->predicted_winner }} to win · {{ $prediction->confidence }}% confidence</div></div></div></section><section class="td-grid"><article class="td-card"><div class="td-label">Model reading</div><p class="td-analysis">{{ $prediction->analysis }}</p>@if($prediction->was_correct !== null)<p class="td-result {{ $prediction->was_correct ? 'td-won' : 'td-lost' }}">{{ $prediction->was_correct ? '✓ Prediction won' : '✕ Prediction lost' }}@if($match->score) · Final score: {{ $match->score }}@endif</p>@endif</article><aside class="td-card"><div class="td-label">Evidence snapshot</div><div class="td-signals"><div class="td-signal"><span>Surface</span><span>{{ ucfirst($match->surface ?: 'Pending') }}</span></div><div class="td-signal"><span>{{ $match->player_one }} recent form</span><span>{{ $one['recent_wins'] ?? '—' }}/{{ $one['recent_matches'] ?? '—' }}</span></div><div class="td-signal"><span>{{ $match->player_two }} recent form</span><span>{{ $two['recent_wins'] ?? '—' }}/{{ $two['recent_matches'] ?? '—' }}</span></div><div class="td-signal"><span>H2H sample</span><span>{{ $h2h['total'] ?? 0 }} match{{ ($h2h['total'] ?? 0) === 1 ? '' : 'es' }}</span></div></div></aside></section></main>
@endsection
