@extends('layouts.app')
@section('title', 'Terms of Service - TavsScore')
@section('meta_description', 'The rules for using TavsScore. We have kept these as short and readable as possible. No hidden traps, no surprising restrictions - just fair terms for using a free football platform.')
@section('canonical', route('terms'))

@section('content')
<div class="wrap" style="max-width:740px; padding-top:2.5rem; padding-bottom:3rem;">

    <nav style="font-size:.72rem; color:var(--text-dim); margin-bottom:1.75rem;">
        <a href="{{ route('home.index') }}" style="color:var(--text-dim); text-decoration:none;">Home</a>
        <span style="margin:0 .4rem; color:var(--text-muted)">›</span>
        <span>Terms of Service</span>
    </nav>

    <h1 style="font-size:2rem; font-weight:900; color:#fff; letter-spacing:-.03em; margin-bottom:.5rem;">Terms of Service</h1>
    <p style="font-size:.82rem; color:var(--text-dim); margin-bottom:2.5rem;">Last updated {{ date('F Y') }}. We have tried to keep these short and readable.</p>

    <div style="background:var(--card); border:1px solid var(--border); border-radius:12px; padding:1.75rem; margin-bottom:1.25rem;">
        <h2 style="font-size:1.05rem; font-weight:800; color:#fff; margin-bottom:.875rem;">The basics</h2>
        <p style="font-size:.88rem; color:var(--text-dim); line-height:1.85; margin-bottom:.875rem;">
            By using TavsScore you agree to these terms. If you do not agree, please do not use the site. These terms apply to everyone who visits TavsScore, whether you are reading match scores, checking predictions, or reading the blog.
        </p>
        <p style="font-size:.88rem; color:var(--text-dim); line-height:1.85;">
            TavsScore is a free service. We reserve the right to change or discontinue any part of it at any time, though we will try to give notice when we can.
        </p>
    </div>

    <div style="background:var(--card); border:1px solid var(--border); border-radius:12px; padding:1.75rem; margin-bottom:1.25rem;">
        <h2 style="font-size:1.05rem; font-weight:800; color:#fff; margin-bottom:.875rem;">What TavsScore is (and is not)</h2>
        <p style="font-size:.88rem; color:var(--text-dim); line-height:1.85; margin-bottom:.875rem;">
            TavsScore provides live football scores, AI-generated match predictions, and editorial content. It is an information and entertainment platform. Full stop.
        </p>
        <p style="font-size:.88rem; color:var(--text-dim); line-height:1.85; margin-bottom:.875rem;">
            <strong style="color:#fff;">TavsScore is not a betting service.</strong> Our predictions are generated by statistical models and AI analysis. They are intended to be interesting and informative, not to help you win money. No prediction on this site should ever be used as the basis for a bet. Football is unpredictable by nature - that is what makes it wonderful - and even the best models are frequently wrong.
        </p>
        <p style="font-size:.88rem; color:var(--text-dim); line-height:1.85;">
            We are not financial advisors, sports betting consultants, or licensed gambling operators. If you have a gambling problem, please contact <a href="https://www.begambleaware.org" target="_blank" rel="noopener" style="color:var(--green);">BeGambleAware</a>.
        </p>
    </div>

    <div style="background:var(--card); border:1px solid var(--border); border-radius:12px; padding:1.75rem; margin-bottom:1.25rem;">
        <h2 style="font-size:1.05rem; font-weight:800; color:#fff; margin-bottom:.875rem;">How you can use TavsScore</h2>
        <p style="font-size:.88rem; color:var(--text-dim); line-height:1.85; margin-bottom:.875rem;">
            You are welcome to read, share links to articles, and use the site for personal enjoyment of football. That is exactly what it is here for.
        </p>
        <p style="font-size:.88rem; color:var(--text-dim); line-height:1.85;">
            A few things we ask you not to do: do not scrape our content or data in bulk without permission, do not attempt to access parts of the site you are not authorised to access, do not use the site for any illegal purpose, and do not try to disrupt the service for other users. We take the last point seriously - if someone is using tools to hammer our servers, we will block them.
        </p>
    </div>

    <div style="background:var(--card); border:1px solid var(--border); border-radius:12px; padding:1.75rem; margin-bottom:1.25rem;">
        <h2 style="font-size:1.05rem; font-weight:800; color:#fff; margin-bottom:.875rem;">Our content</h2>
        <p style="font-size:.88rem; color:var(--text-dim); line-height:1.85; margin-bottom:.875rem;">
            The articles, predictions, and design of TavsScore are our work. You are welcome to quote from them with attribution and a link, but please do not republish them in full without asking first. If you want to syndicate content or partner with us in some way, get in touch - we are open to that.
        </p>
        <p style="font-size:.88rem; color:var(--text-dim); line-height:1.85;">
            Match data comes from API-Football. Team names, league names, and similar factual data are not owned by anyone. AI-generated blog posts are clearly labelled and produced responsibly.
        </p>
    </div>

    <div style="background:var(--card); border:1px solid var(--border); border-radius:12px; padding:1.75rem; margin-bottom:1.25rem;">
        <h2 style="font-size:1.05rem; font-weight:800; color:#fff; margin-bottom:.875rem;">Accuracy of scores and predictions</h2>
        <p style="font-size:.88rem; color:var(--text-dim); line-height:1.85;">
            We make every effort to show accurate, up-to-date scores and fixtures. However, we rely on third-party data providers and occasionally there are delays, errors, or missing results. If you spot something wrong, <a href="{{ route('contact') }}" style="color:var(--green);">let us know</a> and we will look into it. We cannot accept responsibility for decisions made based on data that turned out to be incorrect or delayed.
        </p>
    </div>

    <div style="background:var(--card); border:1px solid var(--border); border-radius:12px; padding:1.75rem; margin-bottom:1.25rem;">
        <h2 style="font-size:1.05rem; font-weight:800; color:#fff; margin-bottom:.875rem;">Advertising</h2>
        <p style="font-size:.88rem; color:var(--text-dim); line-height:1.85;">
            TavsScore is free and supported by advertising through Google AdSense. We do not control which specific ads appear, and we do not endorse any advertiser or product shown on the site. If you see an ad that concerns you, you can report it directly to Google.
        </p>
    </div>

    <div style="background:var(--card); border:1px solid var(--border); border-radius:12px; padding:1.75rem; margin-bottom:1.25rem;">
        <h2 style="font-size:1.05rem; font-weight:800; color:#fff; margin-bottom:.875rem;">Limitation of liability</h2>
        <p style="font-size:.88rem; color:var(--text-dim); line-height:1.85;">
            TavsScore is provided as-is. We do our best, but we cannot guarantee the site will always be available, that scores will always be correct, or that predictions will be accurate. To the extent permitted by law, we are not liable for any losses or damages arising from your use of the site.
        </p>
    </div>

    <div style="background:var(--card); border:1px solid var(--border); border-radius:12px; padding:1.75rem;">
        <h2 style="font-size:1.05rem; font-weight:800; color:#fff; margin-bottom:.875rem;">Updates to these terms</h2>
        <p style="font-size:.88rem; color:var(--text-dim); line-height:1.85; margin-bottom:.875rem;">
            We will update these terms when needed. When we do, the date at the top of the page changes. We will try to post a notice on the site when something important changes. Continued use of TavsScore after an update means you accept the revised terms.
        </p>
        <p style="font-size:.88rem; color:var(--text-dim); line-height:1.85;">
            Any questions about these terms? <a href="{{ route('contact') }}" style="color:var(--green);">Ask us.</a>
        </p>
    </div>

</div>
@endsection
