@extends('layouts.admin')
@section('title','Tennis Predictions')
@section('page-title','Tennis Predictions')
@section('content')
<div class="page-hd"><span class="page-hd-title">🎾 Tennis Predictions</span><div style="display:flex;gap:.5rem;flex-wrap:wrap"><form method="POST" action="{{ route('admin.tennis.fetch') }}">@csrf<button class="btn-a btn-blue">📥 Fetch Fixtures</button></form><form method="POST" action="{{ route('admin.tennis.generate') }}">@csrf<button class="btn-a btn-green">🤖 Generate</button></form><form method="POST" action="{{ route('admin.tennis.settle') }}">@csrf<button class="btn-a btn-gray">✓ Check Results</button></form></div></div>
<div class="a-card" style="display:flex;gap:1rem;align-items:center;flex-wrap:wrap;margin-bottom:1rem;">
    <div style="display:flex;gap:.4rem;align-items:center;">
        <a href="{{ route('admin.tennis.index',['date'=>$dateMeta['prev_iso']]) }}" class="btn-a btn-gray">‹</a>
        <form method="GET"><input type="date" name="date" value="{{ $dateMeta['iso'] }}" min="{{ $dateMeta['min_iso'] }}" max="{{ $dateMeta['max_iso'] }}" onchange="this.form.submit()" style="padding:.4rem;background:var(--bg,#0b1220);border:1px solid var(--border);border-radius:6px;color:var(--text)"></form>
        @if($dateMeta['next_iso'])<a href="{{ route('admin.tennis.index',['date'=>$dateMeta['next_iso']]) }}" class="btn-a btn-gray">›</a>@endif
        @unless($dateMeta['is_today'])<a href="{{ route('admin.tennis.index') }}" class="btn-a btn-blue">Today</a>@endunless
    </div>
    <span style="color:var(--dim);font-size:.82rem;">{{ $dateMeta['pretty'] }}</span>
    @if($winStats['total']>0)<span style="margin-left:auto;font-size:.85rem;color:var(--dim)"><strong style="color:#6ee7b7">Last 30 days:</strong> {{ $winStats['won'] }}/{{ $winStats['total'] }} won · {{ round($winStats['won']/$winStats['total']*100) }}%</span>@endif
</div>
<div class="a-card"><div style="overflow-x:auto"><table class="a-table"><thead><tr><th>Match</th><th>Tour</th><th>Surface</th><th>Time</th><th>Pick</th><th>Confidence</th><th>Result</th></tr></thead><tbody>@forelse($predictions as $prediction)@php($match=$prediction->match)@php($bm=is_array($prediction->features)?($prediction->features['best_market']??null):null)<tr><td style="color:#fff;font-weight:700">{{ $match?->player_one }}@if($match?->player_one_country) <span style="color:#93c5fd;font-size:.68rem">{{ $match->player_one_country }}</span>@endif vs {{ $match?->player_two }}@if($match?->player_two_country) <span style="color:#93c5fd;font-size:.68rem">{{ $match->player_two_country }}</span>@endif<div style="font-size:.68rem;color:var(--dim);margin-top:2px">{{ $match?->tour }} · {{ $match?->tournament }}@if($match?->surface) · {{ $match->surface }}@endif</div></td><td>{{ $match?->tour }}</td><td>{{ $match?->surface }}</td><td style="color:var(--dim);white-space:nowrap">{{ $match?->scheduled_at?->format('M d H:i') ?? $match?->match_date?->format('M d') }}</td><td style="color:#6ee7b7;font-weight:700">{{ $bm['label'] ?? $prediction->predicted_winner }}</td><td>{{ $bm['prob'] ?? $prediction->confidence }}%</td><td>@if($prediction->was_correct === true)<span class="badge badge-green">✓ Won</span>@elseif($prediction->was_correct === false)<span class="badge badge-red">✗ Lost</span>@else<span style="color:var(--dim)">Pending</span>@endif</td></tr>@empty<tr><td colspan="7" style="text-align:center;color:var(--dim);padding:2.5rem">No tennis predictions yet. Fetch fixtures, then generate predictions.</td></tr>@endforelse</tbody></table></div>@if($predictions->hasPages())@include('admin.partials.pagination',['paginator'=>$predictions])@endif</div>
@endsection
